"""Subset Material Symbols to the icons used in src/ and emit a name -> codepoint map.

Usage: uv run --with fonttools --with brotli python scripts/build_icons.py <full-font.woff2>
"""
import json
import re
import sys
from pathlib import Path

from fontTools.subset import Options, Subsetter
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
OUT_FONT = SRC / "fonts" / "material-symbols-subset.woff2"
OUT_MAP = SRC / "components" / "icons.ts"
LITERAL = re.compile(r'(?:name|icon)\s*[=:]\s*\{?\s*([^\n;]+)')
QUOTED = re.compile(r'"([a-z][a-z0-9_]+)"')


def icon_names() -> list[str]:
    names: set[str] = set()
    for path in SRC.rglob("*.tsx"):
        for match in LITERAL.finditer(path.read_text()):
            names.update(QUOTED.findall(match.group(1)))
    return sorted(names)


def ligatures(font: TTFont) -> dict[tuple[str, ...], str]:
    found: dict[tuple[str, ...], str] = {}
    for lookup in font["GSUB"].table.LookupList.Lookup:
        for sub in lookup.SubTable:
            if lookup.LookupType == 7:
                sub = sub.ExtSubTable
            if hasattr(sub, "ligatures"):
                for first, entries in sub.ligatures.items():
                    for lig in entries:
                        found[(first, *lig.Component)] = lig.LigGlyph
    return found


def main(full_font: str) -> None:
    font = TTFont(full_font)
    cmap = font.getBestCmap()
    glyph_to_codepoint = {glyph: cp for cp, glyph in cmap.items()}
    ligs = ligatures(font)
    codepoints: dict[str, int] = {}
    for name in icon_names():
        glyph = ligs.get(tuple(cmap.get(ord(c), "?") for c in name))
        if glyph and glyph in glyph_to_codepoint:
            codepoints[name] = glyph_to_codepoint[glyph]
    options = Options()
    options.flavor = "woff2"
    options.layout_features = []
    options.hinting = False
    subsetter = Subsetter(options)
    subsetter.populate(unicodes=list(codepoints.values()))
    subsetter.subset(font)
    font.save(OUT_FONT)
    entries = ",\n".join(f'  {name}: "\\u{cp:04X}"' for name, cp in codepoints.items())
    OUT_MAP.write_text(
        "// Generated by scripts/build_icons.py. Do not edit by hand.\n"
        f"export const ICONS = {{\n{entries},\n}} as const;\n\n"
        "export type IconName = keyof typeof ICONS;\n"
    )
    print(json.dumps({"icons": len(codepoints), "font_bytes": OUT_FONT.stat().st_size}))


if __name__ == "__main__":
    main(sys.argv[1])
