services:
  nginx:
    image: nginx:1.27-alpine
    container_name: grow-nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./active:/etc/nginx/active:ro
      - ./certbot/conf:/etc/nginx/certs:ro
      - ./certbot/www:/var/www/certbot:ro
    networks:
      - edge
    ports:
      - "80:80"
    restart: unless-stopped

networks:
  edge:
    name: grow-edge
    external: true
